<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="shortcut icon" href="../../source/lang-favicon.png" type="image/x-icon">
     <link rel="stylesheet" href="../../source/style.css">
     <link rel="stylesheet" href="../../source/prism.css">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

     <meta name="description" content="In Python, exceptions are raised when an error or exceptional situation occurs during the execution of a program. To handle and gracefully manage such exceptions, you can use try-except blocks. ">
     <title>Handling exceptions with try-except blocks in Python</title>
</head>
<body>
     <!--Navigation Bar-->
     <header>
          <nav>
               <div class="menu">
                    <h2><a href="../../index.html" class="logo">LangGuides</a></h2>
                    <i class="fa-solid fa-bars" id="open"></i>
                    <i class="fa-solid fa-xmark" id="close"></i>
                 </div>
               <ul class="nav-links">
                    <a href="../../programming/programming-tutorials.html"><li>Programming</li></a>
                    <a href="../../jobinterview/interview-questions.html"><li>Job Interview</li></a>
                    <a href="../../biography/biography-stories.html"><li>Biography</li></a>
                    <a href="../../successstories/sucesss-stories.html"><li>Success Stories</li></a>
                    
                    <a href="../../top10/top10.html"><li>Top 10</li></a>
               </ul>
          </nav>
     </header>

     

     <i class="fa-solid fa-arrow-up" id="up"></i> 
<main> 
<section class="content">
<h1>Handling exceptions with try-except blocks in Python</h1>
<p>In Python, exceptions are raised when an error or exceptional situation occurs during the execution of a program. To handle and gracefully manage such exceptions, you can use try-except blocks. </p>

<article>

<h2>Try Block</h2>
<p>The try block is used to enclose the code that might raise an exception. It is the section of code where you anticipate the occurrence of an exception. If an exception occurs within the try block, it is immediately caught and handled in the corresponding except block.
</p>
<pre><code class="language-py">
try:
     # Code that might raise an exception
     result = x / y
except:
     # Exception handling code
     print("An error occurred.")
</code></pre>
<p>In this example, the code inside the try block performs a division operation that might raise a ZeroDivisionError. If the exception occurs, the control flow jumps to the except block for handling.
</p>

<h2>Except Block</h2>
<p>The except block is used to define the actions to be taken when a specific exception occurs. You can specify the type of exception to catch by using the except statement followed by the exception type. Multiple except blocks can be used to handle different types of exceptions.
</p>
<pre><code class="language-py">
try:
     # Code that might raise an exception
     result = x / y
except ZeroDivisionError:
     # Handling ZeroDivisionError
     print("Cannot divide by zero.")
except ValueError:
     # Handling ValueError
     print("Invalid input value.")
except:
     # Handling any other exceptions
     print("An error occurred.")
 
</code></pre>
<p>In this code, specific except blocks are defined to handle the ZeroDivisionError and ValueError exceptions. The last except block without specifying an exception type will catch any other exceptions that are not caught by the preceding except blocks.
</p>

<h2>Handling Multiple Exceptions</h2>
<p>You can handle multiple exceptions within a single except block by enclosing the exception types in parentheses or by using a tuple.
</p>
<pre><code class="language-py">
try:
     # Code that might raise an exception
     result = x / y
except (ZeroDivisionError, ValueError):
     # Handling ZeroDivisionError and ValueError
     print("An error occurred.")
</code></pre>
<p>In this example, the except block handles both ZeroDivisionError and ValueError exceptions.</p>

<h2>Finally Block</h2>
<p>Optionally, you can include a finally block after the except block. The code in the finally block is executed regardless of whether an exception occurred or not. It is typically used for cleanup actions, such as closing files or releasing resources.
</p>
<pre><code class="language-py">
try:
     # Code that might raise an exception
     result = x / y
except ZeroDivisionError:
     # Handling ZeroDivisionError
     print("Cannot divide by zero.")
finally:
     # Cleanup code
     print("Done with the operation.")
 
</code></pre>
<p>In this code, the finally block will always be executed, irrespective of whether an exception occurred or not.
</p>

<h2></h2>
<p></p>
<pre><code class="language-py">

</code></pre>

</article>

<div class="prev-next">
     <a href="./python-inheritance.html" class="next">Previous</a>
     <a href="./python-modules.html" class="next">Next</a>
</div>

</section>

</main>

<footer>
     <h3><a href="../../index.html" class="logo">LangGuides</a></h3>
     <p>Copyright &#169;	 2023 langguides. All rights reserved</p>
     <a href="../../about/privacy.html">Privacy Policy</a>
     <a href="../../about/terms-of-use.html">Terms of Use</a>
</footer>

<script src="../../source/index.js"></script>
<script src="../../source/prism.js"></script>
</body>
</html>